basePath: /
host: localhost:8001
info:
  contact: {}
  description: API for keyword management
  title: Keyword API
  version: "1.0"
paths:
  /keyword:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: Success
      summary: create a new keyword
swagger: "2.0"
